<script setup>
import { ref } from 'vue'
import { FirstAidKit, Lock, UserFilled } from '@element-plus/icons-vue'
import http from '../api/http'
const emit=defineEmits(['signed-in'])
const mode=ref('login'), login=ref({username:'',password:''}), form=ref({username:'',password:'',idCard:'',name:'',gender:'MALE',birthday:'',phone:'',address:''})
const save=s=>{localStorage.setItem('cloud-hospital-token',s.token);localStorage.setItem('cloud-hospital-session',JSON.stringify(s));emit('signed-in',s)}
const signIn=async()=>save(await http.post('/auth/login',login.value))
const signUp=async()=>save(await http.post('/auth/register',form.value))
</script>
<template><main class="auth"><section><div class="identity"><div class="identity-mark"><el-icon><FirstAidKit/></el-icon></div><h1>云医院</h1><p>让每一次门诊服务更从容有序</p><div class="role"><el-icon><UserFilled/></el-icon><div><b>患者服务</b><span>自助挂号、查看处方与取药通知</span></div></div><div class="role"><el-icon><Lock/></el-icon><div><b>院内工作台</b><span>协同完成挂号、诊疗、收费与发药</span></div></div></div><div class="panel"><div class="panel-title"><h2>{{mode==='login'?'欢迎回来':'创建患者账户'}}</h2><p>{{mode==='login'?'登录后继续您的服务':'填写基本信息，即可使用线上服务'}}</p></div><div class="switch"><button :class="{on:mode==='login'}" @click="mode='login'">登录</button><button :class="{on:mode==='register'}" @click="mode='register'">患者注册</button></div><el-form v-if="mode==='login'" :model="login" label-position="top"><el-form-item label="用户名"><el-input v-model="login.username" autocomplete="username"/></el-form-item><el-form-item label="密码"><el-input v-model="login.password" type="password" show-password autocomplete="current-password" @keyup.enter="signIn"/></el-form-item><el-button type="primary" @click="signIn">登录</el-button><p class="tip">管理员演示账号：admin / admin123</p></el-form><el-form v-else :model="form" label-position="top"><div class="two"><el-form-item label="用户名"><el-input v-model="form.username"/></el-form-item><el-form-item label="密码（至少 6 位）"><el-input v-model="form.password" type="password" show-password/></el-form-item></div><div class="two"><el-form-item label="姓名"><el-input v-model="form.name"/></el-form-item><el-form-item label="性别"><el-radio-group v-model="form.gender"><el-radio value="MALE">男</el-radio><el-radio value="FEMALE">女</el-radio></el-radio-group></el-form-item></div><el-form-item label="身份证号"><el-input v-model="form.idCard"/></el-form-item><div class="two"><el-form-item label="手机号"><el-input v-model="form.phone"/></el-form-item><el-form-item label="出生日期"><el-date-picker v-model="form.birthday" type="date" value-format="YYYY-MM-DD" style="width:100%"/></el-form-item></div><el-form-item label="地址"><el-input v-model="form.address"/></el-form-item><el-button type="primary" @click="signUp">注册并进入患者服务</el-button></el-form></div></section></main></template>
<style scoped>.auth{min-height:100vh;display:grid;place-items:center;padding:24px;background:#edf4f8}.auth section{display:grid;grid-template-columns:.9fr 1.1fr;width:min(980px,100%);background:#fff;border-radius:20px;overflow:hidden;box-shadow:0 24px 60px rgba(23,61,102,.12)}.identity{padding:50px 48px;background:#102f55;color:#fff}.identity-mark{display:grid;place-items:center;width:44px;height:44px;margin-bottom:26px;border-radius:13px;background:#21a68a;font-size:24px}.identity h1{margin:0;font-size:38px;letter-spacing:-.035em}.identity>p{margin:9px 0 38px;color:#b8cde0;font-size:15px}.role{display:flex;gap:13px;align-items:flex-start;margin:22px 0}.role>.el-icon{display:grid;place-items:center;flex:none;width:30px;height:30px;border-radius:9px;background:rgba(255,255,255,.1);color:#86e1ce}.role b,.role span{display:block}.role b{font-size:14px}.role span{margin-top:4px;color:#b8cde0;font-size:13px;line-height:1.6}.panel{padding:44px 48px}.panel-title h2{margin:0;color:#173a5f;font-size:24px;letter-spacing:-.025em}.panel-title p{margin:5px 0 26px;color:#71869b;font-size:13px}.switch{display:flex;gap:25px;margin-bottom:25px;border-bottom:1px solid #e5edf5}.switch button{border:0;background:transparent;padding:0 0 11px;color:#71839a;font-size:15px;cursor:pointer}.switch .on{color:#176b9b;border-bottom:2px solid #176b9b;font-weight:700}.panel .el-button{width:100%;margin-top:6px}.two{display:grid;grid-template-columns:1fr 1fr;gap:14px}.tip{font-size:13px;color:#71839a;margin:16px 0 0}@media(max-width:720px){.auth{padding:0}.auth section{grid-template-columns:1fr;border-radius:0;min-height:100vh}.identity{padding:28px 28px 24px}.identity-mark{width:36px;height:36px;margin-bottom:13px;font-size:19px}.identity h1{font-size:29px}.identity>p{margin:5px 0 0}.role{display:none}.panel{padding:30px 24px}.two{grid-template-columns:1fr}}</style>
