<script setup>
import { ref, onMounted, computed } from 'vue'
import { ElMessage } from 'element-plus'
import http from '../api/http'
const doctors=ref([]), doctorId=ref(null), date=ref(new Date().toISOString().slice(0,10)), queue=ref([]), current=ref(null), record=ref({chiefComplaint:'',presentIllness:'',pastHistory:'',allergyHistory:'',physicalExam:'',diagnosis:'',advice:''})
const rx=ref({remark:'',items:[{drugCode:'D001',drugName:'对乙酰氨基酚片',specification:'0.5g*12片',unit:'盒',unitPrice:12.8,quantity:1,dosage:'0.5g',frequency:'每日3次',route:'口服'}]})
const total=computed(()=>rx.value.items.reduce((n,i)=>n+(Number(i.unitPrice||0)*Number(i.quantity||0)),0).toFixed(2))
const loadDoctors=async()=>{doctors.value=await http.get('/doctors',{params:{enabled:true}});doctorId.value??=doctors.value[0]?.id}
const loadQueue=async()=>{if(!doctorId.value)return;queue.value=await http.get(`/doctors/${doctorId.value}/registrations`,{params:{visitDate:date.value}})}
const start=async r=>{await http.post(`/registrations/${r.id}/start`);ElMessage.success('已开始接诊');await loadQueue();current.value=queue.value.find(x=>x.id===r.id);record.value={chiefComplaint:'',presentIllness:'',pastHistory:'',allergyHistory:'',physicalExam:'',diagnosis:'',advice:''}}
const select=async r=>{current.value=r;try{record.value=await http.get(`/registrations/${r.id}/medical-record`)}catch{record.value={chiefComplaint:'',presentIllness:'',pastHistory:'',allergyHistory:'',physicalExam:'',diagnosis:'',advice:''}}}
const saveRecord=async()=>{if(!current.value)return;await http.put(`/registrations/${current.value.id}/medical-record`,record.value);ElMessage.success('病历已保存')}
const addItem=()=>rx.value.items.push({drugCode:'',drugName:'',specification:'',unit:'盒',unitPrice:0,quantity:1,dosage:'',frequency:'',route:'口服'})
const createRx=async()=>{if(!current.value)return;await http.post(`/registrations/${current.value.id}/prescriptions`,rx.value);ElMessage.success(`处方已开立，总金额 ¥${total.value}`);rx.value={remark:'',items:[]}}
onMounted(loadDoctors)
</script>
<template><div class="page"><div class="toolbar"><el-select v-model="doctorId" placeholder="医生" style="width:240px"><el-option v-for="d in doctors" :key="d.id" :value="d.id" :label="`${d.departmentName} · ${d.realName}`"/></el-select><el-date-picker v-model="date" value-format="YYYY-MM-DD" type="date"/><el-button type="primary" @click="loadQueue">查询待诊队列</el-button></div>
<div class="grid"><el-card header="今日待诊"><el-table :data="queue" height="510" @row-click="select"><el-table-column prop="visitNo" label="流水号" width="150"/><el-table-column prop="patientName" label="患者"/><el-table-column prop="status" label="状态" width="110"><template #default="s"><el-tag :type="s.row.status==='WAITING'?'warning':'primary'">{{s.row.status}}</el-tag></template></el-table-column><el-table-column label="操作" width="100"><template #default="s"><el-button v-if="s.row.status==='WAITING'" type="primary" link @click.stop="start(s.row)">开始接诊</el-button><el-button v-else link @click.stop="select(s.row)">继续</el-button></template></el-table-column></el-table><p class="hint">队列只包含待接诊和接诊中的患者，按挂号时间排序。</p></el-card>
<div><el-card header="门诊病历" v-if="current"><template #header>门诊病历 · {{current.patientName}} <el-tag>{{current.status}}</el-tag></template><el-form :model="record" label-position="top"><el-form-item label="主诉"><el-input v-model="record.chiefComplaint"/></el-form-item><el-form-item label="现病史"><el-input v-model="record.presentIllness" type="textarea" :rows="2"/></el-form-item><el-form-item label="既往史 / 过敏史"><div style="display:flex;gap:8px;width:100%"><el-input v-model="record.pastHistory" placeholder="既往史"/><el-input v-model="record.allergyHistory" placeholder="过敏史"/></div></el-form-item><el-form-item label="体格检查"><el-input v-model="record.physicalExam"/></el-form-item><el-form-item label="初步诊断" required><el-input v-model="record.diagnosis"/></el-form-item><el-form-item label="医嘱"><el-input v-model="record.advice" type="textarea" :rows="2"/></el-form-item><el-button type="primary" @click="saveRecord">保存病历</el-button></el-form></el-card>
<el-card v-if="current" style="margin-top:16px" header="开具处方"><el-table :data="rx.items" size="small"><el-table-column label="药品" min-width="130"><template #default="s"><el-input v-model="s.row.drugName"/></template></el-table-column><el-table-column label="规格" width="120"><template #default="s"><el-input v-model="s.row.specification"/></template></el-table-column><el-table-column label="单价" width="105"><template #default="s"><el-input-number v-model="s.row.unitPrice" :min="0" :precision="2" controls-position="right"/></template></el-table-column><el-table-column label="数量" width="105"><template #default="s"><el-input-number v-model="s.row.quantity" :min="1" controls-position="right"/></template></el-table-column><el-table-column label="用法" width="120"><template #default="s"><el-input v-model="s.row.route"/></template></el-table-column><el-table-column width="60"><template #default="s"><el-button type="danger" link @click="rx.items.splice(s.$index,1)">删除</el-button></template></el-table-column></el-table><div class="toolbar" style="margin-top:12px"><el-button @click="addItem">添加药品</el-button><el-input v-model="rx.remark" placeholder="处方备注"/><span class="amount">合计 ¥{{total}}</span><el-button type="primary" @click="createRx">提交处方</el-button></div></el-card></div>
<el-empty v-if="!current" description="选择一条接诊中的挂号，开始填写病历与处方"/></div></div></template>
