<script setup>
import { ref, onMounted } from 'vue'
import { ElMessage } from 'element-plus'
import http from '../api/http'
const keyword=ref(''), patients=ref([]), doctors=ref([]), selected=ref(null), dialog=ref(false)
const form=ref({ doctorId:null, visitDate:new Date().toISOString().slice(0,10) })
const patientForm=ref({ idCard:'',name:'',gender:'MALE',birthday:'',phone:'',address:'' })
const search=async()=>patients.value=await http.get('/patients',{params:{keyword:keyword.value}})
const loadDoctors=async()=>doctors.value=await http.get('/doctors',{params:{enabled:true}})
const createPatient=async()=>{const p=await http.post('/patients',patientForm.value); selected.value=p; dialog.value=false; patientForm.value={idCard:'',name:'',gender:'MALE',birthday:'',phone:'',address:''}; await search(); ElMessage.success('患者建档成功')}
const register=async()=>{if(!selected.value||!form.value.doctorId)return ElMessage.warning('请选择患者和医生'); await http.post('/registrations',{patientId:selected.value.id,doctorId:form.value.doctorId,visitDate:form.value.visitDate}); ElMessage.success('挂号成功，已进入医生待诊队列')}
onMounted(async()=>{await Promise.all([search(),loadDoctors()])})
</script>
<template><div class="page"><div class="toolbar"><el-input v-model="keyword" placeholder="按姓名或患者编号查询" clearable @keyup.enter="search"/><el-button @click="search">查询</el-button><el-button type="primary" @click="dialog=true">新建患者档案</el-button></div>
<div class="grid"><el-card header="选择患者"><el-table :data="patients" height="360" highlight-current-row @current-change="p=>selected=p"><el-table-column prop="patientNo" label="患者编号" width="150"/><el-table-column prop="name" label="姓名"/><el-table-column prop="gender" label="性别" width="80"/><el-table-column prop="phone" label="电话"/></el-table><p class="hint">当前选择：{{ selected ? `${selected.name}（${selected.patientNo}）` : '未选择' }}</p></el-card>
<el-card header="挂号信息"><el-form label-width="95px"><el-form-item label="就诊医生"><el-select v-model="form.doctorId" placeholder="请选择启用医生" style="width:100%"><el-option v-for="d in doctors" :key="d.id" :value="d.id" :label="`${d.departmentName} · ${d.realName}（${d.title}）`"/></el-select></el-form-item><el-form-item label="就诊日期"><el-date-picker v-model="form.visitDate" value-format="YYYY-MM-DD" type="date" style="width:100%"/></el-form-item><el-form-item><el-button type="primary" size="large" @click="register">确认挂号</el-button></el-form-item></el-form><el-alert type="info" :closable="false" title="规则：同一患者当天不能重复挂同一位医生的未取消号源。"/></el-card></div>
<el-dialog v-model="dialog" title="患者建档" width="520px"><el-form :model="patientForm" label-width="90px"><el-form-item label="身份证号" required><el-input v-model="patientForm.idCard"/></el-form-item><el-form-item label="姓名" required><el-input v-model="patientForm.name"/></el-form-item><el-form-item label="性别"><el-radio-group v-model="patientForm.gender"><el-radio value="MALE">男</el-radio><el-radio value="FEMALE">女</el-radio></el-radio-group></el-form-item><el-form-item label="出生日期"><el-date-picker v-model="patientForm.birthday" value-format="YYYY-MM-DD"/></el-form-item><el-form-item label="电话"><el-input v-model="patientForm.phone"/></el-form-item><el-form-item label="地址"><el-input v-model="patientForm.address"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="createPatient">保存档案</el-button></template></el-dialog></div></template>
